### ISSUE TITLE
submit new module for category (CLI)

### ISSUE THREAD

**Issue by RiedleroD** [ProgrammeYourself/sotodo#6]
basically `sotodo -m "test" "123" default` inserts a new module `test` with the description `123` into the category `default`. Quotes aren't necessary, but encouraged.

**Comment by RiedleroD** [comment]
and -f instead of -m if fixed

**Comment by RiedleroD** [comment]
`sodoto -f name description category`
`sodoto -m name description category`

**Comment by ProgrammeYourself** [comment]
New commands:
```bash
sodoto -f name description category directory
sodoto -m number name description category directory
```
